apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: eqp0jp0q0-python-gitops
  description: This is GitOps manifest for eqp0jp0q0-python   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=eqp0jp0q0-python
    backstage.io/kubernetes-id: eqp0jp0q0-python 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: eqp0jp0q0-python   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:eqp0jp0q0-python
