apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: eqp0jp0q0-python
  janus-idp.io/tekton: eqp0jp0q0-python
  backstage.io/kubernetes-id: eqp0jp0q0-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: eqp0jp0q0-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
